---
all:
  vars:
    ansible_user: admin
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

prod:
  children:
    client1:
      hosts: 10.0.1.4
    client2:
      hosts: 10.0.1.5
  vars:
    ansible_password: admin
