---
- name: "Apache installation using docker"
  hosts: Prod
  become: true
  pre_tasks:
    - name: Install EPEL repo
      package: name={{ item }} state=present update_cache=yes
      #when: ansible_distribution == "CentOS"
      loop:
        - wget
        - git
#Installation de docker
    - name: ensure repository key is installed
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: ensure docker registry is available
      apt_repository: repo='deb https://download.docker.com/linux/ubuntu bionic stable' state=present

    - name: ensure docker and dependencies are installed
      apt: name=docker-ce update_cache=yes

    - service: name=docker state=restarted
#Fin installation Docker et demarrage

    - name: download pip script
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py

    - name: install python-pip
      command: python2.7 /tmp/get-pip.py

    - name: Install docker python
      pip: name=docker-py

    - name: create websites_files
      file:
        path: "/home/{{ ansible_user }}/website_files"
        state: directory

    - name: copy websites_files
      copy:
        src: "/home/admin/ansible_training/website_files/"
        dest: "/home/{{ ansible_user }}/website_files"

    - name: generate index.html file
      template:
        src: "/home/admin/ansible_training/index.html.j2"
        dest: "/home/{{ ansible_user }}/website_files/index.html"

  tasks:
    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
        volumes:
          - "/home/{{ ansible_user }}/website_files/:/usr/local/apache2/htdocs/:z"
